FROM aerospike:latest
RUN echo ========AEROSPIKE_INSTALLING================================================
LABEL maintainer="Luciano Jr <luciano@lucianojr.com.br>"

RUN rm /etc/aerospike/aerospike.conf

ADD aerospike.conf /etc/aerospike/aerospike.conf
